"""empty message

Revision ID: 9f5f85a6ee33
Revises: 01a65ebbf195
Create Date: 2020-04-18 22:54:03.043563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5f85a6ee33'
down_revision = '01a65ebbf195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('enquiry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enquiries', 'enquiry')
    # ### end Alembic commands ###
